FROM oven/bun:latest

WORKDIR /app

COPY package.json ./
COPY bun.lock ./

RUN bun install

COPY . .

EXPOSE 3000

ARG MICROCMS_SERVICE_DOMAIN
ARG MICROCMS_API_KEY
ENV MICROCMS_SERVICE_DOMAIN=$MICROCMS_SERVICE_DOMAIN
ENV MICROCMS_API_KEY=$MICROCMS_API_KEY

RUN bun run build

CMD ["bun", "start"]