apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - ingress.yaml
  - sealedsecret.yaml
  - service.yaml
labels:
  - includeSelectors: true
    pairs:
      app: ayane-utau
