---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCNBiHKk5iery5j9GNSdqoiDnnkuWcMPLZsPHbOtOuGnlDK4ZaavlfS7t+U8v6TdMES7eFdvtixf+oB6f2NhDs0nw0kz6wA5q/MYE4AHmy9GLDzSDycZQV5bVegEB55GJP8PO2TPGjD3LGLGW7LP+ESXecDnrEdKi2MiTBjUi8u1SBigKNUkFqql/DtMBpF/nFnfLvng7/mAGn+QG5NwyGU13IPVKXu+xOn5gCxJMCEZWFKG5dWx2UmMKID1Jb0saaYpxT7DTFPmpwu5NaFzfQvDWpaXWJ4wO5+m3G7o5KpXeT6YR4W6FOljXyq3hJ0LrTfydwzwQlRa5AIY948te5MdWTHFATx/+s/DLXMH/jfBM/fqrVX6u7xIL9LIkhoU9VdKOO6ifnkYSdrgTSMt3KjBMqDHSfjfKByivOh3eMyPtn72FYAsOtSbWMbo2xjR5iUtNqWtauXWIIXr5BymzW1UgRvPv2M2IlOkJhA8PLjFXWEwHPmpR3Ue1OxvvZV1IA2cK/eQAF2ckz0eoRLPh94V0k8z3KKp8ovYGrvmWFipiTTWonzsZcl5WeYSDHFy7lNikOQcMsztho9cn7LNWaHHxlOLEBcX3PV4S6F93LMGlO2F40x5/SLByTsG869lqS5jk2Kr80UMrybeZNIbLw3Hju7US0iUx9VZpRpixquOp7SlYGaF7ldVHZl/l1sh/m7U+dyHmgJXnXhxfCxkTEby7AtsM7ft9qfk2/cfccTk6QSCsTVn7IDxyjLFzlOAf/UGCJt9FYxoQSgOq3CymRqX6iJvG91+b7mP51ywSUYeDfc2l3fe3uBoRAf4UJWtin/McXxj6HVw5wF5e9cXYu6r1A/GMFBgZdvGn1s4NT0cZm/MHnINZ5mFD4gzb5oTXnR620y6Asl
  template:
    metadata:
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
