---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: microcms-secret
  namespace: ayane-utau-site
spec:
  encryptedData:
    apiKey: AgAD8O/PJ9cao9neIvT1aXYZh+IcIMyw1Cvua0qFtJcdbGM0nl3Hu29/06lg/Ax7iuQ3hCVkI99J5TSL96TQ+3rNatfzrTKpZWV7IWd78KpREGUqJtpHujRDOKytcZPyXKZ0OhXobRxcEq2TMFOEmMuA6a03KWhgJKxg6ybChSKn57Iso4gMygeaHGGLmx/ko7eyvCDspEcSpkQVqowFxtMFEi2i9bzQ4Q3QRBViSc4UmZbTt/4gDgiYVejfpWqUmONpojvGVu3bnPuV6xIPOUQP/+yfA+Hn5f7gf1Y785Nldvn9n4jamOSscwFVL5l4noPrmYZa0RrE0qQn+qDXwWLqIorlfBMS7m87lqsvFkEUjbf8KUq3cd80dJE8SR0jcq326ANb/kms3/n7hDKQWTYOGyWJBelBJM9ahCR0Onsa1Jn7v5lFkB/akEgo4hQWGAI/BytSu+dwA1Z5oqsNoloITCslIoft5Xtt2O7KMx7+vprPmYPg1I/ycrvDbHiOZ+ArTjTweUHPdEjiJtApj1ejcKNlygss1OoP3ojAzLLNFSaZqMbqAaHeO5Z4sKux2zikg6W1A7uN/r0WT1sfYW+rjV/xvxQRqP7D1tnzi6NDArSbADDUmf+QxhXEbEOdylxYfGB2WJcjLAEYLnRNCYo9t1Vf/rI+ixrf/j4ykGFTxQbIbcpGbT3XnBZyBYCuULnJbkZ7KXzCKAyd5p6rgqvSIyh5YXq3Wzetq4QLvMdDim22nPk=
    serviceDomain: AgA31dNPUudSLSnSWFGre5Z/mwwhNXaDEznboShza8Lib/BvEYLsbiJp/uiYdswv1fKk4HaRynfSNJ2PAtWmQBIbJEVgaJd86jw6rUZmEdRXEMvrVG38ql6oTlZq1z85TJPzyB3aHL0kc+OuZT6IJtQpwNK6qUnWw9zHBZfTsiHNkMyfbzLQP1W2xTMKwYWMPoOLG5LoP4YC42QH5YQJ+mpvgfM3KQf6E/UNK4lE5Sls+9GtZE0C16+gXAJwoP4VEtEFBtC+9xxSyHM9RYQZAlel+UmwKaIneAgvOyncNtmzwbMv5WVhVI5x7v+jNVfm1T/IqBgN4XQvcyeWAwlVFgRu4xJUYUkOlTXrYbzK9JAX8+ObQx1epoEIw+J4i8hZ2WR7W26mhrMhNhscjEG/RESRQN+8xCukaOEdXZQYpiYU1Qa4lV27F2MPEmNGmfhA0l1oGI9qX7Pflz5+i/Z2Amowi69n+OJJEdToqBCYdZmggD03FjTSAH6WZkwn8BpWtWNwbzgT1C3/Aipp7t6SR7+WFDSHJVSTjNg+6f75XnJyQ9FrHc59aDVxXZUHe7MDzIaV16uLHj/dHwmcNp0f5Kim2247U69RgChN+TEs42DgwdZUDP9DRkO9Z3L9GBMpkyyrBTK9dOjNgY0x72KsUoaniKiA9UPwPq1nJHggtEikioOblWcUfJsR0bGdsk06d3Nwz5zw
  template:
    metadata:
      name: microcms-secret
      namespace: ayane-utau-site
    type: Opaque
